language: ru
toolbar:
  - insertfile undo redo | cut copy paste | styleselect | bold italic |
    alignleft aligncenter alignright alignjustify |
    bullist numlist outdent indent | link image
plugins:
  - advlist
  - anchor
  - autolink
  - charmap
  - code
  - contextmenu
  # - image
  - insertdatetime
  - fullscreen
  - lists
  - link
  - media
  - paste
  - preview
  - print
  - searchreplace
  - table
  - visualblocks
  - wordcount
